import shortid from 'shortid';

// selectors
export const getColumnsForList = ({ columns }, listId) => columns.filter(column => column.listId == listId);

// action name creator
const reducerName = 'columns';
const createActionName = name => `app/${reducerName}/${name}`;


// action types
export const ADD_COLUMN = createActionName('ADD_COLUMN');
console.log('ADD_COLUMN to: ', ADD_COLUMN);

// action creators
export const createActionAddColumn = payload => ({ payload: { ...payload, id: shortid.generate() }, type: ADD_COLUMN });

//reducer
export default function reducer(state = [], action = {}) {
  switch (action.type) {
    case ADD_COLUMN:
      return [...state, action.payload];
    default:
      console.log('state: ', ...state);
      console.log('action.payload: ', action.payload);
      return state;
  }
}

//createActionAddColumn add unique id to the action (it's generated by shirtid.generate() function)
console.log('createActionAddColumn to: ', createActionAddColumn());

console.log('reducer to: ', reducer());